// Generated file, do not edit directly!

declare module 'react-undraw' {
  export interface IllustrationProps {
    primaryColor?: string;
    height?: string;
    style?: object;
    className?: string;
  }

  export interface UndrawProps extends IllustrationProps {
    name: string;
  }

  export default class Undraw extends React.Component<UndrawProps> {
    static setDefaultProps(props: Partial<IllustrationProps>): void;
  }

  export class Undraw3dModeling extends React.Component<IllustrationProps> {}
  export class UndrawADayAtThePark extends React.Component<IllustrationProps> {}
  export class UndrawAWholeYear extends React.Component<IllustrationProps> {}
  export class UndrawAboutMe extends React.Component<IllustrationProps> {}
  export class UndrawAboutUsPage extends React.Component<IllustrationProps> {}
  export class UndrawAcceptTerms extends React.Component<IllustrationProps> {}
  export class UndrawAccount extends React.Component<IllustrationProps> {}
  export class UndrawActiveSupport extends React.Component<IllustrationProps> {}
  export class UndrawAddFiles extends React.Component<IllustrationProps> {}
  export class UndrawAddNotes extends React.Component<IllustrationProps> {}
  export class UndrawAddToCart extends React.Component<IllustrationProps> {}
  export class UndrawAddUser extends React.Component<IllustrationProps> {}
  export class UndrawAddress extends React.Component<IllustrationProps> {}
  export class UndrawAgreement extends React.Component<IllustrationProps> {}
  export class UndrawAirSupport extends React.Component<IllustrationProps> {}
  export class UndrawAircraft extends React.Component<IllustrationProps> {}
  export class UndrawAirport extends React.Component<IllustrationProps> {}
  export class UndrawAlert extends React.Component<IllustrationProps> {}
  export class UndrawAlgolia extends React.Component<IllustrationProps> {}
  export class UndrawAlienScience extends React.Component<IllustrationProps> {}
  export class UndrawAnalysis extends React.Component<IllustrationProps> {}
  export class UndrawAnalytics extends React.Component<IllustrationProps> {}
  export class UndrawAndroid extends React.Component<IllustrationProps> {}
  export class UndrawAppInstallation extends React.Component<IllustrationProps> {}
  export class UndrawAppreciation extends React.Component<IllustrationProps> {}
  export class UndrawArtLover extends React.Component<IllustrationProps> {}
  export class UndrawArtificialIntelligence extends React.Component<IllustrationProps> {}
  export class UndrawAstronaut extends React.Component<IllustrationProps> {}
  export class UndrawAtWork extends React.Component<IllustrationProps> {}
  export class UndrawAuthentication extends React.Component<IllustrationProps> {}
  export class UndrawAutumn extends React.Component<IllustrationProps> {}
  export class UndrawAwards extends React.Component<IllustrationProps> {}
  export class UndrawBaby extends React.Component<IllustrationProps> {}
  export class UndrawBackInTheDay extends React.Component<IllustrationProps> {}
  export class UndrawBackToSchool extends React.Component<IllustrationProps> {}
  export class UndrawBalloons extends React.Component<IllustrationProps> {}
  export class UndrawBarber extends React.Component<IllustrationProps> {}
  export class UndrawBasketball extends React.Component<IllustrationProps> {}
  export class UndrawBeTheHero extends React.Component<IllustrationProps> {}
  export class UndrawBeach extends React.Component<IllustrationProps> {}
  export class UndrawBeerCelebration extends React.Component<IllustrationProps> {}
  export class UndrawBeforeDawn extends React.Component<IllustrationProps> {}
  export class UndrawBeginChat extends React.Component<IllustrationProps> {}
  export class UndrawBibliophile extends React.Component<IllustrationProps> {}
  export class UndrawBirthdayCake extends React.Component<IllustrationProps> {}
  export class UndrawBitcoin extends React.Component<IllustrationProps> {}
  export class UndrawBitcoinP2P extends React.Component<IllustrationProps> {}
  export class UndrawBlankCanvas extends React.Component<IllustrationProps> {}
  export class UndrawBlogPost extends React.Component<IllustrationProps> {}
  export class UndrawBlogging extends React.Component<IllustrationProps> {}
  export class UndrawBookLover extends React.Component<IllustrationProps> {}
  export class UndrawBooking extends React.Component<IllustrationProps> {}
  export class UndrawBookmarks extends React.Component<IllustrationProps> {}
  export class UndrawBrainstorming extends React.Component<IllustrationProps> {}
  export class UndrawBroadcast extends React.Component<IllustrationProps> {}
  export class UndrawBrowserStats extends React.Component<IllustrationProps> {}
  export class UndrawBuddies extends React.Component<IllustrationProps> {}
  export class UndrawBuffer extends React.Component<IllustrationProps> {}
  export class UndrawBugFixing extends React.Component<IllustrationProps> {}
  export class UndrawBuilding extends React.Component<IllustrationProps> {}
  export class UndrawBuildingBlocks extends React.Component<IllustrationProps> {}
  export class UndrawBusStop extends React.Component<IllustrationProps> {}
  export class UndrawBusinessDeal extends React.Component<IllustrationProps> {}
  export class UndrawBusinessPlan extends React.Component<IllustrationProps> {}
  export class UndrawBusinessman extends React.Component<IllustrationProps> {}
  export class UndrawBusinesswoman extends React.Component<IllustrationProps> {}
  export class UndrawByMyCar extends React.Component<IllustrationProps> {}
  export class UndrawCalculator extends React.Component<IllustrationProps> {}
  export class UndrawCalendar extends React.Component<IllustrationProps> {}
  export class UndrawCalling extends React.Component<IllustrationProps> {}
  export class UndrawCampfire extends React.Component<IllustrationProps> {}
  export class UndrawCamping extends React.Component<IllustrationProps> {}
  export class UndrawCareerProgress extends React.Component<IllustrationProps> {}
  export class UndrawCautiousDog extends React.Component<IllustrationProps> {}
  export class UndrawCelebration extends React.Component<IllustrationProps> {}
  export class UndrawCharts extends React.Component<IllustrationProps> {}
  export class UndrawChat extends React.Component<IllustrationProps> {}
  export class UndrawChatting extends React.Component<IllustrationProps> {}
  export class UndrawCheckingBoxes extends React.Component<IllustrationProps> {}
  export class UndrawChecklist extends React.Component<IllustrationProps> {}
  export class UndrawChef extends React.Component<IllustrationProps> {}
  export class UndrawChildren extends React.Component<IllustrationProps> {}
  export class UndrawChilling extends React.Component<IllustrationProps> {}
  export class UndrawChoice extends React.Component<IllustrationProps> {}
  export class UndrawChoose extends React.Component<IllustrationProps> {}
  export class UndrawChristmasStocking extends React.Component<IllustrationProps> {}
  export class UndrawChristmasTree extends React.Component<IllustrationProps> {}
  export class UndrawCircles extends React.Component<IllustrationProps> {}
  export class UndrawCityDriver extends React.Component<IllustrationProps> {}
  export class UndrawCloudHosting extends React.Component<IllustrationProps> {}
  export class UndrawCloudSync extends React.Component<IllustrationProps> {}
  export class UndrawCoWorkers extends React.Component<IllustrationProps> {}
  export class UndrawCoWorking extends React.Component<IllustrationProps> {}
  export class UndrawCoding extends React.Component<IllustrationProps> {}
  export class UndrawCoffeeBreak extends React.Component<IllustrationProps> {}
  export class UndrawCollaboration extends React.Component<IllustrationProps> {}
  export class UndrawCollecting extends React.Component<IllustrationProps> {}
  export class UndrawCollection extends React.Component<IllustrationProps> {}
  export class UndrawCommunity extends React.Component<IllustrationProps> {}
  export class UndrawComposeMusic extends React.Component<IllustrationProps> {}
  export class UndrawConference extends React.Component<IllustrationProps> {}
  export class UndrawConferenceSpeaker extends React.Component<IllustrationProps> {}
  export class UndrawConfirmation extends React.Component<IllustrationProps> {}
  export class UndrawConfirmed extends React.Component<IllustrationProps> {}
  export class UndrawConnected extends React.Component<IllustrationProps> {}
  export class UndrawConnectingTeams extends React.Component<IllustrationProps> {}
  export class UndrawContactUs extends React.Component<IllustrationProps> {}
  export class UndrawContainerShip extends React.Component<IllustrationProps> {}
  export class UndrawContent extends React.Component<IllustrationProps> {}
  export class UndrawContrast extends React.Component<IllustrationProps> {}
  export class UndrawControlPanel extends React.Component<IllustrationProps> {}
  export class UndrawConversation extends React.Component<IllustrationProps> {}
  export class UndrawCountrySide extends React.Component<IllustrationProps> {}
  export class UndrawCouple extends React.Component<IllustrationProps> {}
  export class UndrawCreate extends React.Component<IllustrationProps> {}
  export class UndrawCreationProcess extends React.Component<IllustrationProps> {}
  export class UndrawCreativeThinking extends React.Component<IllustrationProps> {}
  export class UndrawCreativity extends React.Component<IllustrationProps> {}
  export class UndrawCreditCard extends React.Component<IllustrationProps> {}
  export class UndrawCreditCardPayment extends React.Component<IllustrationProps> {}
  export class UndrawCreditCardPayments extends React.Component<IllustrationProps> {}
  export class UndrawCryptoFlowers extends React.Component<IllustrationProps> {}
  export class UndrawCustomerSurvey extends React.Component<IllustrationProps> {}
  export class UndrawDarkAlley extends React.Component<IllustrationProps> {}
  export class UndrawDarkAnalytics extends React.Component<IllustrationProps> {}
  export class UndrawDashboard extends React.Component<IllustrationProps> {}
  export class UndrawData extends React.Component<IllustrationProps> {}
  export class UndrawDataPoints extends React.Component<IllustrationProps> {}
  export class UndrawDataReport extends React.Component<IllustrationProps> {}
  export class UndrawDataTrends extends React.Component<IllustrationProps> {}
  export class UndrawDeliveries extends React.Component<IllustrationProps> {}
  export class UndrawDelivery extends React.Component<IllustrationProps> {}
  export class UndrawDeparting extends React.Component<IllustrationProps> {}
  export class UndrawDepi extends React.Component<IllustrationProps> {}
  export class UndrawDesignCommunity extends React.Component<IllustrationProps> {}
  export class UndrawDesignProcess extends React.Component<IllustrationProps> {}
  export class UndrawDesignThinking extends React.Component<IllustrationProps> {}
  export class UndrawDesignTools extends React.Component<IllustrationProps> {}
  export class UndrawDesigner extends React.Component<IllustrationProps> {}
  export class UndrawDesignerGirl extends React.Component<IllustrationProps> {}
  export class UndrawDesignerLife extends React.Component<IllustrationProps> {}
  export class UndrawDestination extends React.Component<IllustrationProps> {}
  export class UndrawDeveloperActivity extends React.Component<IllustrationProps> {}
  export class UndrawDevelopment extends React.Component<IllustrationProps> {}
  export class UndrawDevices extends React.Component<IllustrationProps> {}
  export class UndrawDigitalNomad extends React.Component<IllustrationProps> {}
  export class UndrawDirections extends React.Component<IllustrationProps> {}
  export class UndrawDiscount extends React.Component<IllustrationProps> {}
  export class UndrawDoctor extends React.Component<IllustrationProps> {}
  export class UndrawDoctors extends React.Component<IllustrationProps> {}
  export class UndrawDocuments extends React.Component<IllustrationProps> {}
  export class UndrawDogWalking extends React.Component<IllustrationProps> {}
  export class UndrawDollPlay extends React.Component<IllustrationProps> {}
  export class UndrawDownload extends React.Component<IllustrationProps> {}
  export class UndrawDreamer extends React.Component<IllustrationProps> {}
  export class UndrawDroneDelivery extends React.Component<IllustrationProps> {}
  export class UndrawDroneRace extends React.Component<IllustrationProps> {}
  export class UndrawDuaLipa extends React.Component<IllustrationProps> {}
  export class UndrawEasterEggHunt extends React.Component<IllustrationProps> {}
  export class UndrawEatingTogether extends React.Component<IllustrationProps> {}
  export class UndrawElectricCar extends React.Component<IllustrationProps> {}
  export class UndrawEmailCampaign extends React.Component<IllustrationProps> {}
  export class UndrawEmailCapture extends React.Component<IllustrationProps> {}
  export class UndrawEmails extends React.Component<IllustrationProps> {}
  export class UndrawEmpty extends React.Component<IllustrationProps> {}
  export class UndrawEnvelope extends React.Component<IllustrationProps> {}
  export class UndrawEnvironment extends React.Component<IllustrationProps> {}
  export class UndrawEther extends React.Component<IllustrationProps> {}
  export class UndrawEthereum extends React.Component<IllustrationProps> {}
  export class UndrawEvents extends React.Component<IllustrationProps> {}
  export class UndrawExams extends React.Component<IllustrationProps> {}
  export class UndrawExperts extends React.Component<IllustrationProps> {}
  export class UndrawExploring extends React.Component<IllustrationProps> {}
  export class UndrawFallIsComing extends React.Component<IllustrationProps> {}
  export class UndrawFans extends React.Component<IllustrationProps> {}
  export class UndrawFastCar extends React.Component<IllustrationProps> {}
  export class UndrawFastLoading extends React.Component<IllustrationProps> {}
  export class UndrawFatherhood extends React.Component<IllustrationProps> {}
  export class UndrawFeaturesOverview extends React.Component<IllustrationProps> {}
  export class UndrawFeelingBlue extends React.Component<IllustrationProps> {}
  export class UndrawFestivities extends React.Component<IllustrationProps> {}
  export class UndrawFileBundle extends React.Component<IllustrationProps> {}
  export class UndrawFileSearching extends React.Component<IllustrationProps> {}
  export class UndrawFilingSystem extends React.Component<IllustrationProps> {}
  export class UndrawFilter extends React.Component<IllustrationProps> {}
  export class UndrawFinance extends React.Component<IllustrationProps> {}
  export class UndrawFinancialData extends React.Component<IllustrationProps> {}
  export class UndrawFinishLine extends React.Component<IllustrationProps> {}
  export class UndrawFireworks extends React.Component<IllustrationProps> {}
  export class UndrawFirmware extends React.Component<IllustrationProps> {}
  export class UndrawFishBowl extends React.Component<IllustrationProps> {}
  export class UndrawFishing extends React.Component<IllustrationProps> {}
  export class UndrawFitnessTracker extends React.Component<IllustrationProps> {}
  export class UndrawFloating extends React.Component<IllustrationProps> {}
  export class UndrawFocus extends React.Component<IllustrationProps> {}
  export class UndrawFollowMeDrone extends React.Component<IllustrationProps> {}
  export class UndrawFollowers extends React.Component<IllustrationProps> {}
  export class UndrawFollowing extends React.Component<IllustrationProps> {}
  export class UndrawForSale extends React.Component<IllustrationProps> {}
  export class UndrawForever extends React.Component<IllustrationProps> {}
  export class UndrawForgotPassword extends React.Component<IllustrationProps> {}
  export class UndrawFreelancer extends React.Component<IllustrationProps> {}
  export class UndrawFriendship extends React.Component<IllustrationProps> {}
  export class UndrawFrozenFigure extends React.Component<IllustrationProps> {}
  export class UndrawGameDay extends React.Component<IllustrationProps> {}
  export class UndrawGaming extends React.Component<IllustrationProps> {}
  export class UndrawGardening extends React.Component<IllustrationProps> {}
  export class UndrawGdpr extends React.Component<IllustrationProps> {}
  export class UndrawGettingCoffee extends React.Component<IllustrationProps> {}
  export class UndrawGift extends React.Component<IllustrationProps> {}
  export class UndrawGiftCard extends React.Component<IllustrationProps> {}
  export class UndrawGifts extends React.Component<IllustrationProps> {}
  export class UndrawGirlsJustWannaHaveFun extends React.Component<IllustrationProps> {}
  export class UndrawGoal extends React.Component<IllustrationProps> {}
  export class UndrawGoingUp extends React.Component<IllustrationProps> {}
  export class UndrawGoldenGateBridge extends React.Component<IllustrationProps> {}
  export class UndrawGoodDoggy extends React.Component<IllustrationProps> {}
  export class UndrawGrades extends React.Component<IllustrationProps> {}
  export class UndrawGraduation extends React.Component<IllustrationProps> {}
  export class UndrawGrandSlam extends React.Component<IllustrationProps> {}
  export class UndrawGrandma extends React.Component<IllustrationProps> {}
  export class UndrawGroupChat extends React.Component<IllustrationProps> {}
  export class UndrawGroupSelfie extends React.Component<IllustrationProps> {}
  export class UndrawGrowing extends React.Component<IllustrationProps> {}
  export class UndrawGrowthAnalytics extends React.Component<IllustrationProps> {}
  export class UndrawHangOut extends React.Component<IllustrationProps> {}
  export class UndrawHappy_2019 extends React.Component<IllustrationProps> {}
  export class UndrawHappyBirthday extends React.Component<IllustrationProps> {}
  export class UndrawHavingFun extends React.Component<IllustrationProps> {}
  export class UndrawHealthyHabit extends React.Component<IllustrationProps> {}
  export class UndrawHeartbroken extends React.Component<IllustrationProps> {}
  export class UndrawHello extends React.Component<IllustrationProps> {}
  export class UndrawHighFive extends React.Component<IllustrationProps> {}
  export class UndrawHiking extends React.Component<IllustrationProps> {}
  export class UndrawHiring extends React.Component<IllustrationProps> {}
  export class UndrawHomeRun extends React.Component<IllustrationProps> {}
  export class UndrawHorrorMovie extends React.Component<IllustrationProps> {}
  export class UndrawHouseSearching extends React.Component<IllustrationProps> {}
  export class UndrawHouses extends React.Component<IllustrationProps> {}
  export class UndrawICanFly extends React.Component<IllustrationProps> {}
  export class UndrawImageFolder extends React.Component<IllustrationProps> {}
  export class UndrawImagePost extends React.Component<IllustrationProps> {}
  export class UndrawImageUpload extends React.Component<IllustrationProps> {}
  export class UndrawImages extends React.Component<IllustrationProps> {}
  export class UndrawInLove extends React.Component<IllustrationProps> {}
  export class UndrawInProgress extends React.Component<IllustrationProps> {}
  export class UndrawInSync extends React.Component<IllustrationProps> {}
  export class UndrawInTheOffice extends React.Component<IllustrationProps> {}
  export class UndrawInThePool extends React.Component<IllustrationProps> {}
  export class UndrawInThought extends React.Component<IllustrationProps> {}
  export class UndrawInboxCleanup extends React.Component<IllustrationProps> {}
  export class UndrawInfluencer extends React.Component<IllustrationProps> {}
  export class UndrawInstantSupport extends React.Component<IllustrationProps> {}
  export class UndrawInteractionDesign extends React.Component<IllustrationProps> {}
  export class UndrawInternetOnTheGo extends React.Component<IllustrationProps> {}
  export class UndrawInterview extends React.Component<IllustrationProps> {}
  export class UndrawInvite extends React.Component<IllustrationProps> {}
  export class UndrawJapan extends React.Component<IllustrationProps> {}
  export class UndrawJasonMask extends React.Component<IllustrationProps> {}
  export class UndrawJavaScriptFrameworks extends React.Component<IllustrationProps> {}
  export class UndrawJobHunt extends React.Component<IllustrationProps> {}
  export class UndrawJogging extends React.Component<IllustrationProps> {}
  export class UndrawJoyride extends React.Component<IllustrationProps> {}
  export class UndrawJudge extends React.Component<IllustrationProps> {}
  export class UndrawLaunching extends React.Component<IllustrationProps> {}
  export class UndrawLighthouse extends React.Component<IllustrationProps> {}
  export class UndrawLiveCollaboration extends React.Component<IllustrationProps> {}
  export class UndrawLoading extends React.Component<IllustrationProps> {}
  export class UndrawLogin extends React.Component<IllustrationProps> {}
  export class UndrawLogistics extends React.Component<IllustrationProps> {}
  export class UndrawLost extends React.Component<IllustrationProps> {}
  export class UndrawLove extends React.Component<IllustrationProps> {}
  export class UndrawLoveIsInTheAir extends React.Component<IllustrationProps> {}
  export class UndrawMail extends React.Component<IllustrationProps> {}
  export class UndrawMailSent extends React.Component<IllustrationProps> {}
  export class UndrawMailbox extends React.Component<IllustrationProps> {}
  export class UndrawMaintenance extends React.Component<IllustrationProps> {}
  export class UndrawMakeItRain extends React.Component<IllustrationProps> {}
  export class UndrawMakerLaunch extends React.Component<IllustrationProps> {}
  export class UndrawMakeupArtist extends React.Component<IllustrationProps> {}
  export class UndrawMakingArt extends React.Component<IllustrationProps> {}
  export class UndrawMap extends React.Component<IllustrationProps> {}
  export class UndrawMapDark extends React.Component<IllustrationProps> {}
  export class UndrawMapLight extends React.Component<IllustrationProps> {}
  export class UndrawMarilyn extends React.Component<IllustrationProps> {}
  export class UndrawMayTheForce extends React.Component<IllustrationProps> {}
  export class UndrawMediaPlayer extends React.Component<IllustrationProps> {}
  export class UndrawMedicine extends React.Component<IllustrationProps> {}
  export class UndrawMeditating extends React.Component<IllustrationProps> {}
  export class UndrawMeditation extends React.Component<IllustrationProps> {}
  export class UndrawMeeting extends React.Component<IllustrationProps> {}
  export class UndrawMessageSent extends React.Component<IllustrationProps> {}
  export class UndrawMessages extends React.Component<IllustrationProps> {}
  export class UndrawMessaging extends React.Component<IllustrationProps> {}
  export class UndrawMessagingFun extends React.Component<IllustrationProps> {}
  export class UndrawMessenger extends React.Component<IllustrationProps> {}
  export class UndrawMillennialGirl extends React.Component<IllustrationProps> {}
  export class UndrawMindMap extends React.Component<IllustrationProps> {}
  export class UndrawMindfulness extends React.Component<IllustrationProps> {}
  export class UndrawMintTea extends React.Component<IllustrationProps> {}
  export class UndrawMissedChances extends React.Component<IllustrationProps> {}
  export class UndrawMissionImpossible extends React.Component<IllustrationProps> {}
  export class UndrawMobile extends React.Component<IllustrationProps> {}
  export class UndrawMobileApps extends React.Component<IllustrationProps> {}
  export class UndrawMobileBrowsers extends React.Component<IllustrationProps> {}
  export class UndrawMobileLife extends React.Component<IllustrationProps> {}
  export class UndrawMobileMarketing extends React.Component<IllustrationProps> {}
  export class UndrawMobilePayments extends React.Component<IllustrationProps> {}
  export class UndrawMobileTesting extends React.Component<IllustrationProps> {}
  export class UndrawModernLife extends React.Component<IllustrationProps> {}
  export class UndrawModernWoman extends React.Component<IllustrationProps> {}
  export class UndrawMomentToRemember extends React.Component<IllustrationProps> {}
  export class UndrawMonitor extends React.Component<IllustrationProps> {}
  export class UndrawMoreMusic extends React.Component<IllustrationProps> {}
  export class UndrawMorningEssentials extends React.Component<IllustrationProps> {}
  export class UndrawMotherhood extends React.Component<IllustrationProps> {}
  export class UndrawMovieNight extends React.Component<IllustrationProps> {}
  export class UndrawMovingForward extends React.Component<IllustrationProps> {}
  export class UndrawMusic extends React.Component<IllustrationProps> {}
  export class UndrawNavigation extends React.Component<IllustrationProps> {}
  export class UndrawNerd extends React.Component<IllustrationProps> {}
  export class UndrawNewMessage extends React.Component<IllustrationProps> {}
  export class UndrawNews extends React.Component<IllustrationProps> {}
  export class UndrawNewsletter extends React.Component<IllustrationProps> {}
  export class UndrawNightCalls extends React.Component<IllustrationProps> {}
  export class UndrawNinja extends React.Component<IllustrationProps> {}
  export class UndrawNoData extends React.Component<IllustrationProps> {}
  export class UndrawNoteList extends React.Component<IllustrationProps> {}
  export class UndrawNotebook extends React.Component<IllustrationProps> {}
  export class UndrawNotes extends React.Component<IllustrationProps> {}
  export class UndrawOffRoad extends React.Component<IllustrationProps> {}
  export class UndrawOldDay extends React.Component<IllustrationProps> {}
  export class UndrawOnTheOffice extends React.Component<IllustrationProps> {}
  export class UndrawOnTheWay extends React.Component<IllustrationProps> {}
  export class UndrawOnboarding extends React.Component<IllustrationProps> {}
  export class UndrawOnline extends React.Component<IllustrationProps> {}
  export class UndrawOnlineFriends extends React.Component<IllustrationProps> {}
  export class UndrawOnlineShopping extends React.Component<IllustrationProps> {}
  export class UndrawOnlineWorld extends React.Component<IllustrationProps> {}
  export class UndrawOpened extends React.Component<IllustrationProps> {}
  export class UndrawOperatingSystem extends React.Component<IllustrationProps> {}
  export class UndrawOrderConfirmed extends React.Component<IllustrationProps> {}
  export class UndrawOrdinaryDay extends React.Component<IllustrationProps> {}
  export class UndrawOrganizePhotos extends React.Component<IllustrationProps> {}
  export class UndrawOrganizeResume extends React.Component<IllustrationProps> {}
  export class UndrawOrganizingProjects extends React.Component<IllustrationProps> {}
  export class UndrawOuterSpace extends React.Component<IllustrationProps> {}
  export class UndrawPageNotFound extends React.Component<IllustrationProps> {}
  export class UndrawPairProgramming extends React.Component<IllustrationProps> {}
  export class UndrawPassingBy extends React.Component<IllustrationProps> {}
  export class UndrawPedestrianCrossing extends React.Component<IllustrationProps> {}
  export class UndrawPenTool extends React.Component<IllustrationProps> {}
  export class UndrawPeopleSearch extends React.Component<IllustrationProps> {}
  export class UndrawPersonalNotes extends React.Component<IllustrationProps> {}
  export class UndrawPersonalSettings extends React.Component<IllustrationProps> {}
  export class UndrawPersonalSite extends React.Component<IllustrationProps> {}
  export class UndrawPersonalTrainer extends React.Component<IllustrationProps> {}
  export class UndrawPersonalization extends React.Component<IllustrationProps> {}
  export class UndrawPhoto extends React.Component<IllustrationProps> {}
  export class UndrawPhotoSharing extends React.Component<IllustrationProps> {}
  export class UndrawPhotocopy extends React.Component<IllustrationProps> {}
  export class UndrawPhotos extends React.Component<IllustrationProps> {}
  export class UndrawPieChart extends React.Component<IllustrationProps> {}
  export class UndrawPilates extends React.Component<IllustrationProps> {}
  export class UndrawPizzaSharing extends React.Component<IllustrationProps> {}
  export class UndrawPlainCreditCard extends React.Component<IllustrationProps> {}
  export class UndrawPlayfulCat extends React.Component<IllustrationProps> {}
  export class UndrawPodcast extends React.Component<IllustrationProps> {}
  export class UndrawPodcastAudience extends React.Component<IllustrationProps> {}
  export class UndrawPortfolio extends React.Component<IllustrationProps> {}
  export class UndrawPost extends React.Component<IllustrationProps> {}
  export class UndrawPostOnline extends React.Component<IllustrationProps> {}
  export class UndrawPostingPhoto extends React.Component<IllustrationProps> {}
  export class UndrawPosts extends React.Component<IllustrationProps> {}
  export class UndrawPowerful extends React.Component<IllustrationProps> {}
  export class UndrawPreferences extends React.Component<IllustrationProps> {}
  export class UndrawPresentation extends React.Component<IllustrationProps> {}
  export class UndrawPressPlay extends React.Component<IllustrationProps> {}
  export class UndrawPrintingInvoices extends React.Component<IllustrationProps> {}
  export class UndrawProcessing extends React.Component<IllustrationProps> {}
  export class UndrawProductHunt extends React.Component<IllustrationProps> {}
  export class UndrawProductTeardown extends React.Component<IllustrationProps> {}
  export class UndrawProductTour extends React.Component<IllustrationProps> {}
  export class UndrawProfile extends React.Component<IllustrationProps> {}
  export class UndrawProfilePic extends React.Component<IllustrationProps> {}
  export class UndrawProgrammer extends React.Component<IllustrationProps> {}
  export class UndrawProgramming extends React.Component<IllustrationProps> {}
  export class UndrawProjections extends React.Component<IllustrationProps> {}
  export class UndrawPrototypingProcess extends React.Component<IllustrationProps> {}
  export class UndrawQaEngineers extends React.Component<IllustrationProps> {}
  export class UndrawQuestions extends React.Component<IllustrationProps> {}
  export class UndrawQueue extends React.Component<IllustrationProps> {}
  export class UndrawQuittingTime extends React.Component<IllustrationProps> {}
  export class UndrawReact extends React.Component<IllustrationProps> {}
  export class UndrawReadingList extends React.Component<IllustrationProps> {}
  export class UndrawRealTimeSync extends React.Component<IllustrationProps> {}
  export class UndrawRecording extends React.Component<IllustrationProps> {}
  export class UndrawRefreshing extends React.Component<IllustrationProps> {}
  export class UndrawRelaxation extends React.Component<IllustrationProps> {}
  export class UndrawRelaxingAtHome extends React.Component<IllustrationProps> {}
  export class UndrawReport extends React.Component<IllustrationProps> {}
  export class UndrawResponsive extends React.Component<IllustrationProps> {}
  export class UndrawResume extends React.Component<IllustrationProps> {}
  export class UndrawResumeFolder extends React.Component<IllustrationProps> {}
  export class UndrawRevenue extends React.Component<IllustrationProps> {}
  export class UndrawRideABicycle extends React.Component<IllustrationProps> {}
  export class UndrawRising extends React.Component<IllustrationProps> {}
  export class UndrawRobotics extends React.Component<IllustrationProps> {}
  export class UndrawRomanticGetaway extends React.Component<IllustrationProps> {}
  export class UndrawRunningWild extends React.Component<IllustrationProps> {}
  export class UndrawSafe extends React.Component<IllustrationProps> {}
  export class UndrawSantaClaus extends React.Component<IllustrationProps> {}
  export class UndrawSavings extends React.Component<IllustrationProps> {}
  export class UndrawSchedule extends React.Component<IllustrationProps> {}
  export class UndrawScience extends React.Component<IllustrationProps> {}
  export class UndrawScooter extends React.Component<IllustrationProps> {}
  export class UndrawScrumBoard extends React.Component<IllustrationProps> {}
  export class UndrawSculpting extends React.Component<IllustrationProps> {}
  export class UndrawSearch extends React.Component<IllustrationProps> {}
  export class UndrawSearchEngines extends React.Component<IllustrationProps> {}
  export class UndrawSecureData extends React.Component<IllustrationProps> {}
  export class UndrawSecureServer extends React.Component<IllustrationProps> {}
  export class UndrawSecurity extends React.Component<IllustrationProps> {}
  export class UndrawSecurityOn extends React.Component<IllustrationProps> {}
  export class UndrawSegment extends React.Component<IllustrationProps> {}
  export class UndrawSegmentation extends React.Component<IllustrationProps> {}
  export class UndrawSelect extends React.Component<IllustrationProps> {}
  export class UndrawSelfie extends React.Component<IllustrationProps> {}
  export class UndrawSelfieTime extends React.Component<IllustrationProps> {}
  export class UndrawServer extends React.Component<IllustrationProps> {}
  export class UndrawServerStatus extends React.Component<IllustrationProps> {}
  export class UndrawSetup extends React.Component<IllustrationProps> {}
  export class UndrawSetupAnalytics extends React.Component<IllustrationProps> {}
  export class UndrawSetupWizard extends React.Component<IllustrationProps> {}
  export class UndrawShopping extends React.Component<IllustrationProps> {}
  export class UndrawSiteStats extends React.Component<IllustrationProps> {}
  export class UndrawSkateboarding extends React.Component<IllustrationProps> {}
  export class UndrawSleepAnalysis extends React.Component<IllustrationProps> {}
  export class UndrawSmartHome extends React.Component<IllustrationProps> {}
  export class UndrawSmileyFace extends React.Component<IllustrationProps> {}
  export class UndrawSnowman extends React.Component<IllustrationProps> {}
  export class UndrawSocialDashboard extends React.Component<IllustrationProps> {}
  export class UndrawSocialGrowth extends React.Component<IllustrationProps> {}
  export class UndrawSocialIdeas extends React.Component<IllustrationProps> {}
  export class UndrawSocialLife extends React.Component<IllustrationProps> {}
  export class UndrawSocialMedia extends React.Component<IllustrationProps> {}
  export class UndrawSocialNetworking extends React.Component<IllustrationProps> {}
  export class UndrawSocialShare extends React.Component<IllustrationProps> {}
  export class UndrawSocialStrategy extends React.Component<IllustrationProps> {}
  export class UndrawSocialTree extends React.Component<IllustrationProps> {}
  export class UndrawSocialUpdate extends React.Component<IllustrationProps> {}
  export class UndrawSoftwareEngineer extends React.Component<IllustrationProps> {}
  export class UndrawSpecs extends React.Component<IllustrationProps> {}
  export class UndrawSpreadsheets extends React.Component<IllustrationProps> {}
  export class UndrawStabilityBall extends React.Component<IllustrationProps> {}
  export class UndrawStarman extends React.Component<IllustrationProps> {}
  export class UndrawStartled extends React.Component<IllustrationProps> {}
  export class UndrawStartupLife extends React.Component<IllustrationProps> {}
  export class UndrawStaticAssets extends React.Component<IllustrationProps> {}
  export class UndrawStatistics extends React.Component<IllustrationProps> {}
  export class UndrawStatusUpdate extends React.Component<IllustrationProps> {}
  export class UndrawStayingIn extends React.Component<IllustrationProps> {}
  export class UndrawStreetFood extends React.Component<IllustrationProps> {}
  export class UndrawStripePayments extends React.Component<IllustrationProps> {}
  export class UndrawStudying extends React.Component<IllustrationProps> {}
  export class UndrawSubway extends React.Component<IllustrationProps> {}
  export class UndrawSuccessfulPurchase extends React.Component<IllustrationProps> {}
  export class UndrawSunnyDay extends React.Component<IllustrationProps> {}
  export class UndrawSuperThankYou extends React.Component<IllustrationProps> {}
  export class UndrawSuperhero extends React.Component<IllustrationProps> {}
  export class UndrawSurfer extends React.Component<IllustrationProps> {}
  export class UndrawSwipeProfiles extends React.Component<IllustrationProps> {}
  export class UndrawSync extends React.Component<IllustrationProps> {}
  export class UndrawTabs extends React.Component<IllustrationProps> {}
  export class UndrawTaken extends React.Component<IllustrationProps> {}
  export class UndrawTakingNotes extends React.Component<IllustrationProps> {}
  export class UndrawTarget extends React.Component<IllustrationProps> {}
  export class UndrawTasting extends React.Component<IllustrationProps> {}
  export class UndrawTeacher extends React.Component<IllustrationProps> {}
  export class UndrawTeaching extends React.Component<IllustrationProps> {}
  export class UndrawTeam extends React.Component<IllustrationProps> {}
  export class UndrawTeamPage extends React.Component<IllustrationProps> {}
  export class UndrawTeamSpirit extends React.Component<IllustrationProps> {}
  export class UndrawTeddyBear extends React.Component<IllustrationProps> {}
  export class UndrawTexting extends React.Component<IllustrationProps> {}
  export class UndrawThoughts extends React.Component<IllustrationProps> {}
  export class UndrawThroughTheDesert extends React.Component<IllustrationProps> {}
  export class UndrawTimeManagement extends React.Component<IllustrationProps> {}
  export class UndrawTimeline extends React.Component<IllustrationProps> {}
  export class UndrawToDo extends React.Component<IllustrationProps> {}
  export class UndrawToDoList extends React.Component<IllustrationProps> {}
  export class UndrawToTheStars extends React.Component<IllustrationProps> {}
  export class UndrawTogether extends React.Component<IllustrationProps> {}
  export class UndrawToyCar extends React.Component<IllustrationProps> {}
  export class UndrawTrackAndField extends React.Component<IllustrationProps> {}
  export class UndrawTransferFiles extends React.Component<IllustrationProps> {}
  export class UndrawTravelBooking extends React.Component<IllustrationProps> {}
  export class UndrawTravelers extends React.Component<IllustrationProps> {}
  export class UndrawTraveling extends React.Component<IllustrationProps> {}
  export class UndrawTreasure extends React.Component<IllustrationProps> {}
  export class UndrawTrip extends React.Component<IllustrationProps> {}
  export class UndrawTrueFriends extends React.Component<IllustrationProps> {}
  export class UndrawTweetstorm extends React.Component<IllustrationProps> {}
  export class UndrawTypewriter extends React.Component<IllustrationProps> {}
  export class UndrawTyping extends React.Component<IllustrationProps> {}
  export class UndrawUnboxing extends React.Component<IllustrationProps> {}
  export class UndrawUnderConstruction extends React.Component<IllustrationProps> {}
  export class UndrawUpdate extends React.Component<IllustrationProps> {}
  export class UndrawUpgrade extends React.Component<IllustrationProps> {}
  export class UndrawUpload extends React.Component<IllustrationProps> {}
  export class UndrawUploadImage extends React.Component<IllustrationProps> {}
  export class UndrawUploading extends React.Component<IllustrationProps> {}
  export class UndrawUpvote extends React.Component<IllustrationProps> {}
  export class UndrawUsabilityTesting extends React.Component<IllustrationProps> {}
  export class UndrawUserFlow extends React.Component<IllustrationProps> {}
  export class UndrawVault extends React.Component<IllustrationProps> {}
  export class UndrawVehicleSale extends React.Component<IllustrationProps> {}
  export class UndrawVersionControl extends React.Component<IllustrationProps> {}
  export class UndrawVideoCall extends React.Component<IllustrationProps> {}
  export class UndrawVideographer extends React.Component<IllustrationProps> {}
  export class UndrawVirtualReality extends React.Component<IllustrationProps> {}
  export class UndrawVisualData extends React.Component<IllustrationProps> {}
  export class UndrawVoiceControl extends React.Component<IllustrationProps> {}
  export class UndrawVrChat extends React.Component<IllustrationProps> {}
  export class UndrawWalkInTheCity extends React.Component<IllustrationProps> {}
  export class UndrawWallPost extends React.Component<IllustrationProps> {}
  export class UndrawWallet extends React.Component<IllustrationProps> {}
  export class UndrawWarning extends React.Component<IllustrationProps> {}
  export class UndrawWeather extends React.Component<IllustrationProps> {}
  export class UndrawWebDevices extends React.Component<IllustrationProps> {}
  export class UndrawWebsiteSetup extends React.Component<IllustrationProps> {}
  export class UndrawWedding extends React.Component<IllustrationProps> {}
  export class UndrawWelcome extends React.Component<IllustrationProps> {}
  export class UndrawWindTurbine extends React.Component<IllustrationProps> {}
  export class UndrawWindowShopping extends React.Component<IllustrationProps> {}
  export class UndrawWindows extends React.Component<IllustrationProps> {}
  export class UndrawWinners extends React.Component<IllustrationProps> {}
  export class UndrawWinterDesigner extends React.Component<IllustrationProps> {}
  export class UndrawWinterOlympics extends React.Component<IllustrationProps> {}
  export class UndrawWireframing extends React.Component<IllustrationProps> {}
  export class UndrawWishes extends React.Component<IllustrationProps> {}
  export class UndrawWitch extends React.Component<IllustrationProps> {}
  export class UndrawWoman extends React.Component<IllustrationProps> {}
  export class UndrawWomenDay extends React.Component<IllustrationProps> {}
  export class UndrawWordOfMouth extends React.Component<IllustrationProps> {}
  export class UndrawWordpress extends React.Component<IllustrationProps> {}
  export class UndrawWorkChat extends React.Component<IllustrationProps> {}
  export class UndrawWorkTime extends React.Component<IllustrationProps> {}
  export class UndrawWorking extends React.Component<IllustrationProps> {}
  export class UndrawWorkingLate extends React.Component<IllustrationProps> {}
  export class UndrawWorkingRemotely extends React.Component<IllustrationProps> {}
  export class UndrawWorkout extends React.Component<IllustrationProps> {}
  export class UndrawXmasSurprise extends React.Component<IllustrationProps> {}
  export class UndrawYacht extends React.Component<IllustrationProps> {}
  export class UndrawYoungAndHappy extends React.Component<IllustrationProps> {}
  export class UndrawYoutubeTutorial extends React.Component<IllustrationProps> {}
}
